spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bifriends_test
    username: bifriends
    password: bifriends

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: false

  sql:
    init:
      mode: always
      data-locations: classpath:db/math_seed.sql,classpath:db/korean_seed.sql
